name: Embedded C CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ARM GCC Toolchain
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi

      - name: Build firmware
        run: make

      - name: Run unit tests (host build)
        run: make test

      - name: Run static analysis (cppcheck)
        run: cppcheck --enable=all --inconclusive --suppress=missingIncludeSystem --error-exitcode=1 -I./src src tests

