name: Cppcheck Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cppcheck python3 \
                                 gcc-arm-none-eabi binutils-arm-none-eabi wget
          # Install cppcheck-htmlreport manually (not available via pip)
          wget https://raw.githubusercontent.com/danmar/cppcheck/main/htmlreport/cppcheck-htmlreport \
               -O /usr/local/bin/cppcheck-htmlreport
          chmod +x /usr/local/bin/cppcheck-htmlreport

      - name: Run cppcheck and generate XML
        run: |
          cppcheck --enable=all --inconclusive --xml --xml-version=2 \
            -I./src src tests 2> cppcheck-report.xml

      - name: Generate HTML report
        run: |
          cppcheck-htmlreport --file=cppcheck-report.xml \
                              --report-dir=cppcheck-html-report \
                              --source-dir=.

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-html-report
          path: cppcheck-html-report
          
      - name: Install ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git
          ./esp-idf/install.sh
          . ./esp-idf/export.sh
      
      - name: Build ESP32 firmware
        run: idf.py build

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: build/*.bin

