name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cppcheck python3 python3-pip \
                                 gcc-arm-none-eabi binutils-arm-none-eabi
          pip install cppcheck-htmlreport

      - name: Build firmware
        run: make

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: firmware.elf

      - name: Run unit tests (host side)
        run: ./tests/test_math || true   # skip failure if embedded code can't run on CI

      - name: Run cppcheck and generate XML + HTML report
        run: |
          cppcheck --enable=all --inconclusive --xml --xml-version=2 -I./src src tests 2> cppcheck-report.xml
          cppcheck-htmlreport \
            --file=cppcheck-report.xml \
            --report-dir=cppcheck-html \
            --source-dir=.

      - name: Upload static analysis report
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck-report
          path: cppcheck-html
