name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cppcheck
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Build
        run: make

      - name: Run unit tests (host side)
        run: ./tests/test_math || true   # embedded code may not run on CI runner

      - name: Run static analysis (cppcheck)
        run: cppcheck --enable=all --inconclusive --suppress=missingIncludeSystem --error-exitcode=1 -I./src src tests
